### Concatenation work like if axis=k (which has to be <n (dimension of the matrix)) , then keep opening the brackets k times and concatenate remaining elements from both matrix and then close brackets again 

In [14]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)
print("---------")
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]
---------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [26]:
import numpy as np

arr1 = np.array([[[1, 2], [3, 4]],[[5,6], [7, 8]]])

arr2 = np.array([[[11, 21], [31, 41]],[[51,61], [71, 81]]])

arr = np.concatenate((arr1, arr2), axis=2)
print(arr)
print("---------")
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)
print("---------")
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[[ 1  2 11 21]
  [ 3  4 31 41]]

 [[ 5  6 51 61]
  [ 7  8 71 81]]]
---------
[[[ 1  2]
  [ 3  4]
  [11 21]
  [31 41]]

 [[ 5  6]
  [ 7  8]
  [51 61]
  [71 81]]]
---------
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[11 21]
  [31 41]]

 [[51 61]
  [71 81]]]


In [8]:
import numpy as np
a = np.array([[1, 2]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))  
print("----------")
print(np.concatenate((a, b), axis=1))  



[[1 2]
 [5 6]]
----------
[[1 2 5 6]]


## Stacking

### stack increases dimension of resultant matix by 1 after stacking

In [38]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)
arr_ = np.concatenate((arr1, arr2), axis=0)


print(arr)
print(arr_)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [36]:
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [47]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4],[11,12]])       # passed 2D matrix

arr2 = np.array([[5, 6], [7, 8],[51, 61]])

arr = np.stack((arr1, arr2), axis=2)
print(arr)
print("--------------")
arr = np.stack((arr1, arr2), axis=1)
print(arr)
print("--------------")
arr = np.stack((arr1, arr2), axis=0)
print(arr)

[[[ 1  5]
  [ 2  6]]

 [[ 3  7]
  [ 4  8]]

 [[11 51]
  [12 61]]]
--------------
[[[ 1  2]
  [ 5  6]]

 [[ 3  4]
  [ 7  8]]

 [[11 12]
  [51 61]]]
--------------
[[[ 1  2]
  [ 3  4]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [51 61]]]


In [7]:
print(np.stack((a, b), axis=0))  # Adds a new axis  
print("----------")
print(np.stack((a, b), axis=1))  # Adds a new axis  



[[[1 2]]

 [[5 6]]]
----------
[[[1 2]
  [5 6]]]


In [9]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
arr = np.concatenate((arr1, arr2))
print(arr)
# arr = np.concatenate((arr1, arr2),axis=1)     # shows :- AxisError: axis 1 is out of bounds for array of dimension 1


[1 2 3 4 5 6]
